import type { Metadata } from 'next';
import { Montserrat, Raleway } from 'next/font/google';
import { notFound } from 'next/navigation';
import { Locale } from '../../types/locale';

import '../globals.css';

const locales: Locale[] = ['en', 'uk'];

const montserrat = Montserrat({
  subsets: ['cyrillic', 'latin'],
  display: 'swap',
  variable: '--font-montserrat',
});
const raleway = Raleway({
  subsets: ['cyrillic', 'latin'],
  display: 'swap',
  variable: '--font-raleway',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: Locale };
}) {
  const isValidLocale = locales.some(cur => cur === locale);
  if (!isValidLocale) notFound();

  return (
    <html lang={locale}>
      <body className={`${montserrat.variable} ${raleway.variable}`}>
        {children}
        <div id="modal" />
      </body>
    </html>
  );
}
