#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '
┌─┐┌┬┐┌─┐┬─┐┌┬┐
└─┐ │ ├─┤├┬┘ │ 
└─┘ ┴ ┴ ┴┴└─ ┴ '

# Formatting
npm run fix 

git add .

# Check ESLint Standards
npm run lint ||
(
        echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false;
)

# # If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright... Code looks good to me... Run test-all script 🤔🤔🤔🤔'

npm run test-all ||
(
    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why.
    '
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅  

  You are amazing 
          \
          |\___/|
         =) oYo (=            
          \  ^  /
           )=*=(       
          /     \
          |     |
         /| | | |\
         \| | |_|/\
         //_// ___/
             \_) 

✅✅✅✅'
