import type { Metadata } from 'next';
import { Montserrat, Raleway } from 'next/font/google';
import { Locale, i18n } from '@/i18n.config';

import '../globals.css';
import { Header } from '@/layout/Header';
import { getCommonDictionaries } from '@/lib/dictionary';

const montserrat = Montserrat({
  subsets: ['cyrillic', 'latin'],
  display: 'swap',
  variable: '--font-montserrat',
});
const raleway = Raleway({
  subsets: ['cyrillic', 'latin'],
  display: 'swap',
  variable: '--font-raleway',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// export async function generateStaticParams() {
//   return i18n.locales.map(locale => ({ lang: locale }));
// }

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  const { common } = await getCommonDictionaries(params.lang);

  return (
    <html lang={params.lang}>
      <body className={`${montserrat.variable} ${raleway.variable}`}>
        <Header data={common.header} />
        <main>{children}</main>
        <div id="modal" />
      </body>
    </html>
  );
}
